### ISSUE TITLE
Outlier styles not updating

### ISSUE THREAD

**Issue by LovelyAndy** [sgratzl/chartjs-chart-boxplot#29]
When I try and update the `outlierStyle`, `BackgroundColor`, `Radius` or any of the other styles, nothing seems to happen and the outlier stays the same tiny grey circle.

**To Reproduce**

1. Following the examples online, I have put the style in the datasets array, but still no updates.

**Expected behavior**

All of the styles chosen in the datesets array should show on the chart itself, but only the border styles update.
`outlierBackgroundColor` should be orange per my line of `outlierBackgroundColor: "#FF0000"`

**Screenshots**

This is the style I am going for 
![image](https://user-images.githubusercontent.com/68723584/167682498-50497b48-1d07-45b4-a197-bf4d3266858a.png)

But this is the style that I can make:
![image](https://user-images.githubusercontent.com/68723584/167682568-c3b77296-8b25-4405-af82-2b18fd1e21c6.png)

**Context**

- Version:  "@sgratzl/chartjs-chart-boxplot": "^3.7.2"
- Browser: Chrome

**Additional context**
I've made a stackoverflow post trying to get some answers, but so far nothing has come up
https://stackoverflow.com/questions/72189935/how-to-change-chartjs-boxplot-outlier-style

Also, I made a codesandbox for it as well 
https://codesandbox.io/s/crazy-goodall-jy28zt?file=/src/components/BoxPlotChart.vue

Cheers on this plugin though! I've never used a boxplot and was really struggling until I found this! Thanks for all your hard work and look forward to your reply!

**Comment by sgratzl** [comment]
random data tends to have no outliers. 

e.g. in your example if you show this values:

```
[...randomValues(100, 60, 100), 130, 150]
```

you will see 
![image](https://user-images.githubusercontent.com/4129778/167704665-7c77d1f9-e931-4337-b22c-f7385574bd4b.png)

**Comment by LovelyAndy** [comment]
> , 130, 150
Thanks for the quick reply! Wow, there they are!
Where are you putting these numbers exactly? If I put them in the data array after the random values the outliers still don't render. 
I have never really worked with a boxplot before, programming or otherwise, so I apologize if this is a really silly question.

**Comment by LovelyAndy** [comment]
, 130, 150
Thanks for the quick reply! Wow, there they are!
Where are you putting these numbers exactly? If I put them in the data array after the random values the outliers still don't render.
I have never really worked with a boxplot before, programming or otherwise, so I apologize if this is a really silly question.

**Comment by sgratzl** [comment]
in order to understand what an outlier represents you first have to understand the basic elements of a boxplot. 

A boxplot is a summary of collection of values highlighting some important values. First the the median (line in the middle of the box). Then the 25% and 75% quantile (which form the box). The dot next to the median line is the mean of the values. The whiskers (T-shapes) stretch depending on the configuration. By default it is the 25% quantile - 1.5* (75% quantile - 25% quantile) and 75% quantile + 1.5 ... respectively. An outlier is then a datapoint which is below or above the whiskers, i.e. the are outliers from the basic distribution the boxplot is showing. 

In the example above:
```
[...randomValues(100, 60, 100), 130, 150]
```
you can read it as: generate 100 random values between 60 and 100 + add two extra values 130 and 150. The majority of the values will be a uniform distribution of values between 60 and 100 which will drive the boxplot. 130 and 150 are clear outside of the normal area and thus marked as outliers in the chart.
